import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google"
import Hero from "@/components/home/hero";
import Header from "@/components/header";
import Footer from "@/components/footer";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    display: "swap",
})


export const metadata: Metadata = {
  title: "Noka.Ai ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      {/* <TopBanner /> */}
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}
